language: ruby
rvm:
  - 2.1.1
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - rake deps:rb
  #- rake deps:pl
  - sudo apt-get install libqtwebkit-dev
  - rake deps:js
script:
  - rake test:rb
  - rake test:js
  #- prove -I tests/pl/lib -I . -lr tests
